"""Generate deterministic Python-reference values for the Episode 007 browser core.

Run from the repository root with:
    uv run python episodes/007-limit-cycle-interactive-widget/scripts/generate_browser_model_fixture.py
"""
from __future__ import annotations

import json
from pathlib import Path

from bergner_spichtinger_2026.constants import Environment
from bergner_spichtinger_2026.core import coefficients, equilibrium, process_terms, vector_field

ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "episodes/007-limit-cycle-interactive-widget/web/src/fixtures/python-model-reference.json"
CASES = {
    "canonical": (Environment(30_000, 225, 0.1, 1, 1e10, 100), (50_000.0, 6e-6, 1.5)),
    "low_boundary": (Environment(15_000, 190, 0.005, 0.05, 3e8, 50), (5_000.0, 2e-7, 1.55)),
    "high_boundary": (Environment(60_000, 235, 2, 1, 1e10, 500), (400_000.0, 2e-4, 1.45)),
}


def values(x: object) -> object:
    if hasattr(x, "item"):
        return x.item()
    return x


def main() -> None:
    fixture: dict[str, object] = {"provenance": "Generated by src/bergner_spichtinger_2026/core.py; do not edit manually.", "cases": {}}
    cases: dict[str, object] = fixture["cases"]  # type: ignore[assignment]
    for name, (env, state) in CASES.items():
        c = coefficients(env)
        n, q, s = state
        eq = equilibrium(env)
        cases[name] = {
            "environment": {"T": env.T, "p": env.p, "w": env.w, "F": env.F, "N_a": env.N_a, "deltaZ": env.Δz},
            "state": {"n": n, "q": q, "s": s},
            "coefficients": {key.replace("ρ", "rho").replace("p_si", "pSi"): values(value) for key, value in c.__dict__.items()},
            "terms": {key: values(value) for key, value in process_terms(n, q, s, env, c).items()},
            "vectorField": dict(zip(("n", "q", "s"), map(values, vector_field(n, q, s, env, c)))),
            "equilibrium": dict(zip(("n", "q", "s"), map(values, eq))),
        }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(fixture, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
